### ISSUE TITLE
how to write to multiple files?

### ISSUE THREAD

**Issue by veeramarni** [mcollina/sonic-boom#13]
Do you have an example for writing to multiple files base on filter condition? For example, when writing json log data, we want to write different logfiles based on the input data with `id`. So we have `file1.log, file2.log etc.`.

**Comment by mcollina** [comment]
It is not a feature provided by this module, and I’d call it out of scope. This module enables to write at high throughput.
You will have to use multiple instance of sonic boom, one for each id.
