### ISSUE TITLE
Strings are truncated to 64kb in Docker

### ISSUE THREAD

**Issue by aikoven** [mcollina/sonic-boom#16]
I'm trying to write long strings (actually JSON lines) to stdout, but they get truncated. I could only reproduce this in Docker, but not in Node.js for Mac. I also get full output when using `process.stdout.write(...)`.

**Comment by mcollina** [comment]
Oh interesting! Would you mind creating a quick repository with a way to reproduce? I'll have a look.
We should probably cut the buffer at 64KB.

This is bypassing some checks that Node.js does for speed purposes.

**Comment by aikoven** [comment]
I started making a repro repo, and noticed that you've already published a fix, and it indeed fixed the issue. Thanks!
