### ISSUE TITLE
flatstr version update

### ISSUE THREAD

**Issue by luddite478** [mcollina/sonic-boom#27]
Hi, i am getting an error `SyntaxError: Unexpected token %` on line 242 in index.js. It's related to old flatstr package version. New 1.0.12 is just simple oneliner and it won't cause this error, for sure.

So could you update flatstr version from 1.0.9 to 1.0.12 in your package.json, please?

**Comment by mcollina** [comment]
This should get picked up automatically if you update your dependencies.
Removed your package-lock and node_modules folders and reinstall.
