### ISSUE TITLE
Cannot use namespace 'SonicBoom' as a type.

### ISSUE THREAD

**Issue by jontroncoso** [mcollina/sonic-boom#44]
When using `@types/pino` for pino which has sonic-boom as a dependency and uses `@types/sonic-boom` for the types, I get `Cannot use namespace 'SonicBoom' as a type.`. After tracking this down this has to do with a discrepancy between `@types/sonic-boom` and `sonicboom/types/index.d.ts`.

Specifically:

```
export default SonicBoom;
```
should be
```
export = SonicBoom;
```

**Comment by jontroncoso** [comment]
If you're gettin this, a solution for me was to explicitly use 
```
"sonic-boom": "1.1.0",
```
In any repository that used an internal pino-wrapper package that depended on pino (which depends on sonic-boom)

**Comment by jontroncoso** [comment]
If you can somehow fix the `@types/pino` repo You may be able to leave this how it is.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pino/index.d.ts#L23

Specifically change
```
import SonicBoom = require('sonic-boom');
```
to
```
import SonicBoom from 'sonic-boom';
```

But I don't know which is easier to do

**Comment by mcollina** [comment]
@kibertoad ptal.

**Comment by mcollina** [comment]
@jontroncoso the easiest way is for you to send a PR.

**Comment by kibertoad** [comment]
IIRC correctly, export = x requires esinterop enabled and we removed it from other places, such as fastify-swagger, for same reason.
I'll take a look if it can be fixed in non-breaking way.

**Comment by kibertoad** [comment]
@mcollina Instead of changing types-pino, we can merge the pino types PR, that would fix problem as well, but yes, for sonic-boom this likely should have been a semver major.

**Comment by mcollina** [comment]
I'm reverting the types here asap.

**Comment by jontroncoso** [comment]
> @jontroncoso the easiest way is for you to send a PR.

Sure. But, I wasn't sure if you which direction you wanted to go. Anyway, thanks for addressing so quickly.
