### ISSUE TITLE
write enormously large buffers async test fails on 14.13.0

### ISSUE THREAD

**Issue by puzpuzpuz** [mcollina/sonic-boom#48]
I'm getting the following error in the test on Node.js 14.13.0 (same for 14.12.0):
```
  test: write enormously large buffers async
  stack: |
    SonicBoom.write (index.js:190:16)
    Test.<anonymous> (test.js:689:14)
  type: RangeError
  tapCaught: testFunctionThrow
```

**Comment by puzpuzpuz** [comment]
The failure is probably related with this regression in V8's max supported string length: https://github.com/v8/v8/commit/ea56bf5513d0cbd2a35a9035c5c2996272b8b728

Considering this, the fix should be to reduce the string length by x2 in the test.

**Comment by mcollina** [comment]
Done .. I pushed directly to master.
