### ISSUE TITLE
After fs.write throw, it may cause a memory leak.

### ISSUE THREAD

**Issue by xiedacon** [mcollina/sonic-boom#54]
When `fs.write` throw an error, `this._writing` is set to `true` and there is no way to set it to `false`. https://github.com/mcollina/sonic-boom/blob/master/index.js#L94

If the user does not listen to the error event, no one can know what happened. And because of `this._writing = true`, all the following write data will be appended to `this._buf`, which will eventually lead to a memory leak.

So, should sonic-boom follow this?

> No matter any error occurs, `this._writing` should be set to `false`, then it can be retried by the following write.

**Comment by xiedacon** [comment]
Same with reopen. https://github.com/mcollina/sonic-boom/blob/master/index.js#L29

Maybe sonic-boom should write the data to the old file.

**Comment by mcollina** [comment]
>If the user does not listen to the error event, no one can know what happened. And because of this._writing = true, all the following write data will be appended to this._buf, which will eventually lead to a memory leak.

Then the process should crash. The memory leak would not happen unless you have an `uncaughtException` handler that prevent the process from crashing. 

---

Overall I'm ok in changing this behavior and making sonic-boom more resilient. Would you like to send a PR with a unit test?
